version: '3.8'
services:
  web:
    image: ghcr.io/sajjadgholamipour/fastapi-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: web.logs

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis.logs

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:9.1.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
